language: generic
sudo: required
sevices:
  - docker

before_install:
  - docker build -t yomarguti/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true yomarguti/docker-react-udemy npm run test
